// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://napqmdzxzpxfyxegqxjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcHFtZHp4enB4Znl4ZWdxeGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzM5NDUsImV4cCI6MjA2ODk0OTk0NX0.UZR15X7Zc-IRl-eykMurJ3Ha_4kIhp2Bn58svfAaEdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});